Line and bar chart
Basiol97/cryptoApp pull request #2
Opened 2023-01-09 15:15 UTC by Basiol97

Integrated the Chart-js to display the fetched data in the form of line and bar charts.

2023-01-09 16:10 UTC, yoloOnTheBattlefield requested changes

2023-01-09 16:10 UTC, yoloOnTheBattlefield commented on src/components/Pages/LoadingPage/components/LandingPage.js
> +        const currentDate = mm + " " + dd + ', ' + yyyy;
const currentDate = `${mm } " " + dd + ', ' + yyyy;

2023-01-09 16:10 UTC, yoloOnTheBattlefield commented on src/components/Pages/LoadingPage/components/LandingPage.js
> +    }
add in a separate file

2023-01-09 16:10 UTC, yoloOnTheBattlefield commented on src/components/Pages/LoadingPage/components/Line.js
> +}
make this a functional component

2023-01-09 16:10 UTC, yoloOnTheBattlefield commented on src/components/Pages/LoadingPage/styled/LandingPage.styled.js
> +`;
indent

2023-01-10 17:16 UTC, Basiol97 commented on src/components/Pages/LoadingPage/components/LandingPage.js
> +        const currentDate = mm + " " + dd + ', ' + yyyy;
Resolved by implementing moment js

2023-01-10 17:30 UTC, Basiol97 commented on src/components/Pages/LoadingPage/components/Line.js
> +}
Resolved

2023-02-17 22:03 UTC, closed without merging