Portfolio and coin page
Basiol97/cryptoApp pull request #6
Opened 2023-02-03 15:40 UTC by Basiol97

The portfolio page, coin page and nav-bar component were built and styled. In addition, major styling (responsiveness) improvements were made to the CoinList page.

2023-02-03 16:41 UTC, yoloOnTheBattlefield requested changes

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/App.js
> +import NavBar from "components/NavBar";
new line

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/App.js
> +            ConverMode={ConverMode}
camelCase

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/Description/index.js
> +            />
dangerously set inner html

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/MobileNavbar/index.js
> +        <Search onClick={() => props.handleMobileSearchClick()}>
<Search onClick={ props.handleMobileSearchClick}>

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/MobileNavbar/styled.js
> +}
indented

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/MobileNavbar/styled.js
> +box-shadow: 0px 0px 10px 3px rgba(0,0,0,0.3);
same here

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/NavBar/index.js
> +                        if (item == "") {
double check this

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/NavBar/index.js
> +                            to={`coinpage/${item.id}`}
`/coinpage/${item.id}`

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/NavBar/index.js
> +                  onChange={(e) => props.handleCurrencyChange(e)}
onChange={props.handleCurrencyChange}

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/components/NavBar/index.js
> +              <ThemeContainer onClick={() => props.ConverMode()}>
make it shorter

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/pages/CoinList/CoinList.js
> +      setfetedData(response);
typo

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/pages/CoinPage/CoinPage.js
> +      setfetedData(response);
typo

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/pages/Portfolio/Portfolio.js
> +  }, [props.currencyType]);
useEffect(fetchData, [props.currencyType]);

2023-02-03 16:41 UTC, yoloOnTheBattlefield commented on src/pages/Portfolio/Portfolio.js
> +  }, [props.currencyType]);
try this

2023-02-06 15:26 UTC, Basiol97 commented on src/App.js
> +import NavBar from "components/NavBar";
Resloved

2023-02-06 15:26 UTC, Basiol97 commented on src/App.js
> +import NavBar from "components/NavBar";
Resolved

2023-02-06 15:26 UTC, Basiol97 commented on src/App.js
> +            ConverMode={ConverMode}
Resolved

2023-02-06 15:32 UTC, Basiol97 commented on src/components/MobileNavbar/index.js
> +        <Search onClick={() => props.handleMobileSearchClick()}>
Resolved

2023-02-06 15:32 UTC, Basiol97 commented on src/components/MobileNavbar/styled.js
> +}
Resolved

2023-02-06 15:34 UTC, Basiol97 commented on src/components/NavBar/index.js
> +                  onChange={(e) => props.handleCurrencyChange(e)}
Resolved

2023-02-06 15:35 UTC, Basiol97 commented on src/pages/CoinList/CoinList.js
> +      setfetedData(response);
Resolved

2023-02-06 15:36 UTC, Basiol97 commented on src/pages/CoinPage/CoinPage.js
> +      setfetedData(response);
Resolved

2023-02-06 15:39 UTC, Basiol97 commented on src/pages/Portfolio/Portfolio.js
> +  }, [props.currencyType]);
Solution didn't work as expected

2023-02-06 15:40 UTC, Basiol97 commented on src/components/MobileNavbar/styled.js
> +box-shadow: 0px 0px 10px 3px rgba(0,0,0,0.3);
Resolved

2023-02-06 15:40 UTC, Basiol97 commented on src/components/NavBar/index.js
> +                        if (item == "") {
Resolved

2023-02-06 15:40 UTC, Basiol97 commented on src/components/NavBar/index.js
> +                            to={`coinpage/${item.id}`}
Resolved

2023-02-06 15:44 UTC, merged